
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_password
      POSTGRES_DB: bookstore
    volumes:
      - ./_data:/var/lib/postgresql/data
      - ./internal/authors/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  authors:
    build:
      context: .
      dockerfile: Dockerfile_authors
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
  books:
    build:
      context: .
      dockerfile: Dockerfile_books
    restart: always
    depends_on:
      - redis
    ports:
      - 9090:9090
  orders:
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    build:
      context: .
      dockerfile: Dockerfile_orders
    # restart: always
    depends_on:
      - mongo
    ports:
      - 9999:9999
  gateway:
    environment:
      - AUTHORS_URL=http://authors:8080
      - BOOKS_URL=http://books:9090
      - ORDERS_URL=http://orders:9999
    build:
      context: .
      dockerfile: Dockerfile_gateway
    restart: always
    depends_on:
      - authors
      - books
      - orders
    ports:
      - 10000:10000
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"