FROM golang:1.22 as builder
WORKDIR /app
COPY go.mod go.sum /app/
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -a -installsuffix cgo -o main cmd/orders/main.go
FROM golang:1.22
WORKDIR /app
COPY --from=builder  /app/main .
CMD [ "/app/main" ]