FROM golang:1.22 as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux   GOARCH=amd64  go build -a -installsuffix cgo -o main cmd/authors/main.go
FROM golang:1.22
WORKDIR /app
COPY --from=builder  /app/main .
CMD [ "/app/main" ]