FROM golang:1.22 as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOOS=linux go build -a -installsuffix cgo -o  main cmd/books/main.go
FROM golang:1.22
WORKDIR /app
COPY --from=builder /app/main .
RUN chmod +x /app/main
CMD [ "/app/main" ]