scrape_configs:
- job_name: authors
  scrape_interval: 10s
  static_configs:
  - targets:
    - authors:8080

- job_name: books
  scrape_interval: 10s
  static_configs:
  - targets:
    - books:9090

- job_name: orders
  scrape_interval: 10s
  static_configs:
  - targets:
    - orders:9999

- job_name: gateway
  scrape_interval: 10s
  static_configs:
  - targets:
    - gateway:10000