// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books,omitempty"`
}

type AuthorQueryInput struct {
	ID string `json:"id"`
}

type AuthorsQueryInput struct {
	IDs []string `json:"IDs"`
}

type Book struct {
	ID            string  `json:"id"`
	Title         string  `json:"title"`
	Author        *Author `json:"author"`
	PublishedDate string  `json:"publishedDate"`
}

type BookQueryInput struct {
	ID string `json:"id"`
}

type BooksQueryInput struct {
	IDs []string `json:"IDs"`
}

type CreateAuthorInput struct {
	Name string `json:"name"`
}

type CreateBookInput struct {
	Title         string `json:"title"`
	AuthorID      string `json:"authorId"`
	PublishedDate string `json:"publishedDate"`
}

type CreateOrderInput struct {
	OrderLines []*OrderLineInput `json:"orderLines"`
	TotalPrice int               `json:"totalPrice"`
	OrderDate  string            `json:"orderDate"`
}

type DeleteAuthorInput struct {
	ID string `json:"id"`
}

type DeleteBookInput struct {
	ID string `json:"id"`
}

type DeleteOrderInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Order struct {
	ID         string `json:"id"`
	Book       *Book  `json:"book"`
	Quantity   int    `json:"quantity"`
	TotalPrice int    `json:"totalPrice"`
	OrderDate  string `json:"orderDate"`
}

type OrderLineInput struct {
	BookID   string `json:"bookID"`
	Quantity int    `json:"quantity"`
}

type OrderQueryInput struct {
	ID string `json:"id"`
}

type OrdersQueryInput struct {
	TotalPrice *int    `json:"totalPrice,omitempty"`
	OrderDate  *string `json:"orderDate,omitempty"`
	Limit      *int    `json:"limit,omitempty"`
	Offset     *int    `json:"offset,omitempty"`
}

type Query struct {
}

type UpdateAuthorInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateBookInput struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	AuthorID      string `json:"authorId"`
	PublishedDate string `json:"publishedDate"`
}

type UpdateOrderInput struct {
	ID         string            `json:"id"`
	OrderLines []*OrderLineInput `json:"orderLines,omitempty"`
	OrderDate  string            `json:"orderDate"`
	TotalPrice int               `json:"totalPrice"`
}
